services:
  db:
    image: postgres:14.4
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    container_name: cinesearchdb
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
