export * from "./AdminDashboard";
export * from "./Detail";
export * from "./Error404/Error404";
export * from "./Home";
export * from "./RegistrarPelicula";
export * from "./Reserve";
export * from "./user/Logout";
export * from "./user/login/Login";
export * from "./user/register/Register";
export * from "./Gallery"