export * from './Dashboard/AdminDashboard';
export * from './Dashboard/movies/EditarPelicula';
export * from './Dashboard/movies/ListaPeliculas';
export * from './Dashboard/movies/RegistrarPelicula';
export * from './Dashboard/users/AgregarUsuario';
export { default as EditarUsuario } from './Dashboard/users/EditarUsuario';
export { default as EliminarUsuario } from './Dashboard/users/EliminarUsuario';
export { default as ListUsers } from './Dashboard/users/ListUsers';
export * from './Detail';
export * from './Error404/Error404';
export * from './Gallery';
export * from './Reserve';
export { default as NewReserve } from './NewReserve';
export * from './home/Home';
export * from './user/Logout';
export * from './user/Setting';
export * from './user/login/Login';
export { default as Profile } from './user/profile/Profile';
export * from './user/register/Register';
export { default as Favorite} from './Favorite'