name: Deploy Frontend on AWS S3

on:
  push:
    branches:
      - frontend
    paths:
      - frontend/**/*

jobs:
  avoid_reduncy:
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.12.0
        with:
          access_token: ${{ github.token }}

  dependencies:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4.0.0
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "frontend/*"
      - name: Installing dependencies
        run: cd frontend && npm install

  tests:
    needs: [dependencies]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4.0.0
        with:
          cache: "npm"
          node-version: "20"
          cache-dependency-path: "frontend/*"
      - name: Installing dependencies
        run: cd frontend && npm ci
      - name: Testing
        run: cd frontend && echo "Test failure..."

  build:
    needs: [dependencies]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4.0.0
        with:
          cache: "npm"
          node-version: "20"
          cache-dependency-path: "frontend/*"
      - name: Installing dependencies
        run: cd frontend && npm ci
      - name: Building
        run: cd frontend && npm run build
      - uses: actions/upload-artifact@v3.1.3
        with:
          name: dist
          path: frontend/dist

  deploy:
    needs: [build]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Set AWS credentials
        if: ${{ github.event_name == 'push' }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: frontend/dist
      - name: Deploy to AWS S3
        run: aws s3 sync ./frontend/dist/. s3://1023c12-grupo2-pi
